# SPDX-FileCopyrightText: 2023 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

version: 2
builds:
  - goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    files:
      - src: ./exporter/templates/*
        dst: templates
