# SPDX-FileCopyrightText: 2023 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

build_dir := "./build"
set dotenv-path := "../.env"
set dotenv-load
set shell := ["bash", "-ceo", "pipefail"]

default:
  just --list

gotest:
  #!/bin/bash
  set -aeuxo pipefail
  CGO_CXXFLAGS="-I${SLURM_INCLUDE_DIR}"
  CGO_LDFLAGS="-L${SLURM_LIB_DIR} -lslurmfull"
  LD_LIBRARY_PATH="$SLURM_LIB_DIR"
  go test

cpptest:
  rm -rf {{build_dir}}/test && mkdir -p {{build_dir}}/test
  g++ test/node_test.cpp slurmcprom.cpp -I. -I${SLURM_INCLUDE_DIR} -L${SLURM_LIB_DIR} -lslurmfull -o {{build_dir}}/test/node_test
  LD_LIBRARY_PATH=$SLURM_LIB_DIR {{build_dir}}/test/node_test
